###############################################################################
# Environment script generated by ilcsoft-install on Tue May 22 14:05:34 2018
# for the installation located at [ /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-01 ]
################################################################################

SET( ILC_HOME "/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v02-00-02" CACHE PATH "Path to ILC Software" FORCE)
MARK_AS_ADVANCED( ILC_HOME )

SET( CMAKE_PREFIX_PATH
	${ILC_HOME}/lccd/v01-05;
	${ILC_HOME}/Marlin/v01-16;
	${ILC_HOME}/MarlinDD4hep/v00-06;
	${ILC_HOME}/DDMarlinPandora/v00-10;
	${ILC_HOME}/MarlinUtil/v01-15;
	${ILC_HOME}/MarlinReco/v01-25;
	${ILC_HOME}/PandoraAnalysis/v02-00-00;
	${ILC_HOME}/PandoraPFANew/v03-09-00;
	${ILC_HOME}/LCFIVertex/v00-07-04;
	${ILC_HOME}/CEDViewer/v01-16;
	${ILC_HOME}/Overlay/v00-21;
	${ILC_HOME}/MarlinFastJet/v00-05-01;
	${ILC_HOME}/LCTuple/v01-11;
	${ILC_HOME}/MarlinKinfit/v00-06;
	${ILC_HOME}/MarlinTrk/v02-07;
	${ILC_HOME}/KiTrack/v01-09;
	${ILC_HOME}/KiTrackMarlin/v01-12;
	${ILC_HOME}/MarlinTrkProcessors/v02-10;
	${ILC_HOME}/MarlinKinfitProcessors/v00-04;
	${ILC_HOME}/ILDPerformance/v01-06;
	${ILC_HOME}/Clupatra/v01-03;
	${ILC_HOME}/Physsim/v00-04-01;
	${ILC_HOME}/LCFIPlus/v00-06-09;
	${ILC_HOME}/FCalClusterer/v01-00;
	${ILC_HOME}/ForwardTracking/v01-13;
	${ILC_HOME}/ConformalTracking/v01-07;
	${ILC_HOME}/LICH/v00-01;
	${ILC_HOME}/pathfinder/v00-06-01;
	${ILC_HOME}/MarlinTPC/v01-04;
	${ILC_HOME}/bbq/v00-01-03;
	${ILC_HOME}/Garlic/v03-01;
	${ILC_HOME}/RAIDA/v01-09;
	${ILC_HOME}/KalTest/v02-05;
	${ILC_HOME}/KalDet/v01-14-01;
	${ILC_HOME}/GBL/V02-01-01;
	${ILC_HOME}/xercesc/3.1.4;
	${ILC_HOME}/DD4hep/v01-07-02;
	${ILC_HOME}/lcgeo/v00-16-03;
	${ILC_HOME}/aidaTT/v00-09;
	${ILC_HOME}/DDKalTest/v01-05;
	${ILC_HOME}/DD4hepExamples/v01-07-02;
	${ILC_HOME}/CED/v01-09-02;
	${ILC_HOME}/lcio/v02-12-01;
	${ILC_HOME}/gear/v01-08;
	${ILC_HOME}/FastJet/3.2.1;
	${ILC_HOME}/root/6.08.06;
	${ILC_HOME}/CLHEP/2.3.4.3;
	${ILC_HOME}/gsl/2.1;
	${ILC_HOME}/QT/4.7.4;
	${ILC_HOME}/geant4/10.03.p02;
	${ILC_HOME}/CondDBMySQL/CondDBMySQL_ILC-0-9-6;
	${ILC_HOME}/mysql/5.0.45;
	${ILC_HOME}/ilcutil/v01-05;
	/cvmfs/ilc.desy.de/sw/boost/1.58.0;
	/cvmfs/ilc.desy.de/sw/Eigen/3.2.9;
CACHE PATH "CMAKE_PREFIX_PATH" FORCE )

option(USE_CXX11 "Use cxx11" True)
option(Boost_NO_BOOST_CMAKE "dont use cmake find module for boost" ON)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g" CACHE STRING "" FORCE )

# calice code installation directory

SET( CALICE_HOME
     "${CMAKE_CURRENT_SOURCE_DIR}"
     CACHE PATH "Path to CALICE Software" FORCE )
MARK_AS_ADVANCED( CALICE_HOME )

# calice cmake module directory

SET( CMAKE_MODULE_PATH
     "${CALICE_HOME}/cmake"
     CACHE PATH "Path to CMake Modules" FORCE )

#################################################
## Set the installation prefix,
## i.e. the directory where you want your libraries
## and binaries to be installed.
#################################################
SET( CMAKE_INSTALL_PREFIX "${CALICE_HOME}/myInstall"
     CACHE PATH "Install prefix" FORCE)

#################################################
##
## CALICE packages
##
#################################################
SET( CALICE_USERLIB_HOME "${CALICE_HOME}/calice_userlib/cmake"
     CACHE PATH "Path to calice_userlib" FORCE )

SET( CALICE_RECO_HOME "${CALICE_HOME}/calice_reco/cmake"
     CACHE PATH "Path to calice_reco" FORCE )

SET( RAW2CALOHIT_HOME "${CALICE_HOME}/calice_reco/raw2calohit/cmake"
     CACHE PATH "Path to calice_reco/raw2calohit" FORCE )

SET( CLUSTERING_HOME "${CALICE_HOME}/calice_reco/clustering/cmake"
     CACHE PATH "Path to calice_reco/clustering" FORCE )

SET( LABVIEW2LCIO_DIR "${CALICE_HOME}/labview_converter/raw2lcio/cmake"
     CACHE PATH "Path to labview_converter" FORCE )

SET( CELLGEOMETRY_DIR "${CALICE_HOME}/calice_reco/cellGeometry/cmake"
     CACHE PATH "Path to calice_reco/cellGeometry" FORCE )

SET( RECOSIPM_DIR "${CALICE_HOME}/calice_reco/recoSiPM/cmake"
     CACHE PATH "Path to calice_reco/recoSiPM" FORCE )
