################################################################################
# Environment script generated by CMake on 2016-06-20 00:16:28
# for the installation located at [ /home/calice/Desktop/ILCSoftInstall/ilcsoft ]
################################################################################

SET( ILC_HOME "/home/calice/Desktop/ILCSoftInstall/ilcsoft" CACHE PATH "Path to ILC Software" FORCE)
MARK_AS_ADVANCED( ILC_HOME )

SET( CMAKE_PREFIX_PATH
	 ${ILC_HOME}/CLHEP/2.1.4.1;
	 ${ILC_HOME}/GSL/1.14;
	 ${ILC_HOME}/xerces/3.1.3;
	 ${ILC_HOME}/ilcutil/v01-02-01;
	 ${ILC_HOME}/CED/v01-09-02;
	 ${ILC_HOME}/QT/4.7.4;
	 ${ILC_HOME}/CondDBMySQL/CondDBMySQL_ILC-0-9-6;
	 ${ILC_HOME}/root/5.34.36;
	 ${ILC_HOME}/MarlinUtil/v01-09;
	 ${ILC_HOME}/Marlin/v01-08;
	 ${ILC_HOME}/LCIO/v02-07;
	 ${ILC_HOME}/lccd/v01-03;
	 ${ILC_HOME}/gear/v01-05;
	 ${ILC_HOME}/boost/1.58.0;
	 ${ILC_HOME}/mysql/5.1.73;
CACHE PATH "CMAKE_PREFIX_PATH" FORCE )

# calice code installation directory

SET( CALICE_HOME 
     "${CMAKE_SOURCE_DIR}"
     CACHE PATH "Path to CALICE Software" FORCE )
MARK_AS_ADVANCED( CALICE_HOME )

# calice cmake module directory

SET( CMAKE_MODULE_PATH 
     "${CALICE_HOME}/cmake"
     CACHE PATH "Path to CMake Modules" FORCE )

#################################################
## Set the installation prefix, 
## i.e. the directory where you want your libraries
## and binaries to be installed.
#################################################
SET( CMAKE_INSTALL_PREFIX "${CALICE_HOME}/myInstall"
     CACHE PATH "Install prefix" FORCE)

#################################################
##
## CALICE packages
## 
#################################################
SET( CALICE_USERLIB_HOME "${CALICE_HOME}/calice_userlib/cmake"
     CACHE PATH "Path to calice_userlib" FORCE )

SET( CALICE_RECO_HOME "${CALICE_HOME}/calice_reco/cmake"
     CACHE PATH "Path to calice_reco" FORCE )

SET( RAW2CALOHIT_HOME "${CALICE_HOME}/calice_reco/raw2calohit/cmake"
     CACHE PATH "Path to calice_reco/raw2calohit" FORCE )

SET( CLUSTERING_HOME "${CALICE_HOME}/calice_reco/clustering/cmake"
     CACHE PATH "Path to calice_reco/clustering" FORCE )

SET( LABVIEW2LCIO_DIR "${CALICE_HOME}/labview-converter/raw2lcio/cmake"
     CACHE PATH "Path to labview_converter" FORCE )

SET( CELLGEOMETRY_DIR "${CALICE_HOME}/calice_reco/cellGeometry/cmake"
     CACHE PATH "Path to calice_reco/cellGeometry" FORCE )

SET( RECOSIPM_DIR "${CALICE_HOME}/calice_reco/recoSiPM/cmake"
     CACHE PATH "Path to calice_reco/recoSiPM" FORCE )
